# Generated by Django 3.2.8 on 2021-10-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipAddress', models.CharField(max_length=20)),
                ('time', models.DateTimeField()),
                ('successfull', models.IntegerField(default=0)),
                ('unsuccessfull', models.IntegerField(default=0)),
            ],
        ),
    ]
